version: '3'
services:
  # web:
  #   image: node:latest
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   depends_on:
  #     - kafka
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #       - "3000:3000"
  #   command: npm start
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://infrastructure.test:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 2000024
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2097152
    networks:
      default:
        aliases:
          - "infrastructure.test"